# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "awesome-terragrunt-project-tf-state"
    key     = "dev/network/terraform.tfstate"
    region  = "us-east-1"
    encrypt = true
  }
}
